FROM golang:1.22 AS builder
WORKDIR /gateway
COPY . .

ENV GOPROXY=https://goproxy.io/

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -x -o ./build/main .

FROM alpine:latest
WORKDIR /gateway

COPY --from=builder /gateway/build/main .
COPY ./key ./key

CMD ["./main"]
