# 默认开启80端口
# 如果配置ssl,则自动开启443端口并将访问80端口的请求转到443端口
[ssl]
ssl_cert_fp = "example.crt"
ssl_key_fp = "example.pem"

[[proxy]]
source = "http://example.com"
target = "http://localhost:8001"

[[proxy]]
source = "http://example2.com"
target = "http://localhost:8002"

[[proxy]]
source = "http://api.example.com"
target = "http://localhost:8003/api"

[assets]
source = "http://assets.example.com"
strip_prefix = "/assets"
#此处应该使用 docker -v local/path:to\your\path\ 的方式挂载资源目录
dir = 'to\your\path\'