port = [
    80,
    443
]

[[proxy]]
source = "http://example.com"
target = "http://localhost:8001"

[[proxy]]
source = "http://example2.com"
target = "http://localhost:8002"

[[proxy]]
source = "http://api.example.com"
target = "http://localhost:8003/api"

[assets]
source = "http://assets.example.com"
strip_prefix = "/assets"
#此处应该使用 docker -v local/path:to\your\path\ 的方式挂载资源目录
dir = 'to\your\path\'